# docker-compose.yml

version: '3'  # You can remove this line if it's obsolete

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    container_name: audio-visualizer-app-backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Needed for live reload in Docker
    networks:
      - app-network
    depends_on:
      - backend
    container_name: audio-visualizer-app-frontend

networks:
  app-network:
    driver: bridge

